"""Add indexes

Revision ID: 095e86301f11
Revises: 61c6062ee0bf
Create Date: 2020-06-13 14:38:44.797272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095e86301f11'
down_revision = '61c6062ee0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_title', table_name='projects')
    op.create_index(op.f('ix_user_project_role_id'), 'user_project', ['role_id'], unique=False)
    op.create_index('user_name', 'users', ['first_name', 'last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_name', table_name='users')
    op.drop_index(op.f('ix_user_project_role_id'), table_name='user_project')
    op.create_index('ix_projects_title', 'projects', ['title'], unique=False)
    # ### end Alembic commands ###
