"""Add roles table

Revision ID: 0c23633c2017
Revises: 56bdda34ba80
Create Date: 2020-05-19 01:10:07.589683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c23633c2017'
down_revision = '56bdda34ba80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=9), nullable=False),
        sa.Column('permissions', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.drop_column('user_project', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project', sa.Column('role', sa.String(length=9), nullable=True))
    op.execute("UPDATE user_project SET role = 'Admin';")
    op.alter_column('user_project', 'role', nullable=False)
    op.drop_table('roles')
    # ### end Alembic commands ###
