"""Add files table

Revision ID: 17f8d20c0242
Revises: 25fc3a09eb5c
Create Date: 2020-07-13 23:16:59.172317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f8d20c0242'
down_revision = '25fc3a09eb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('size', sa.String(), nullable=False),
        sa.Column('timestamp', sa.Float(), nullable=False),
        sa.Column('uploader_id', sa.Integer(), nullable=False),
        sa.Column('issue_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['issue_id'], ['issues.id'],),
        sa.ForeignKeyConstraint(['uploader_id'], ['users.id'],),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('issue_id', 'filename', name='issue_filename'),
    )
    op.create_index(op.f('ix_files_timestamp'), 'files', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_timestamp'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
