"""Change user_project table's name to user_projects and add timestamp column

Revision ID: 2a9081f3781c
Revises: 7d5bf549ec5b
Create Date: 2020-06-30 14:09:48.058128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9081f3781c'
down_revision = '7d5bf549ec5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_projects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index(op.f('ix_user_projects_timestamp'), 'user_projects', ['timestamp'], unique=False)
    op.drop_index('ix_user_project_role_id', table_name='user_project')
    op.drop_table('user_project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_project',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='user_project_project_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_project_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_project_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', name='user_project_pkey')
    )
    op.create_index('ix_user_project_role_id', 'user_project', ['role_id'], unique=False)
    op.drop_index(op.f('ix_user_projects_timestamp'), table_name='user_projects')
    op.drop_table('user_projects')
    # ### end Alembic commands ###
