"""Add resolved_timestamp and closed_timestamp columns

Revision ID: 5c8a1c8c431c
Revises: 47b483da6c00
Create Date: 2020-07-18 17:04:37.247227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8a1c8c431c'
down_revision = '47b483da6c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('closed_timestamp', sa.Float(), nullable=True))
    op.add_column('issues', sa.Column('resolved_timestamp', sa.Float(), nullable=True))
    op.create_index(
        op.f('ix_issues_closed_timestamp'), 'issues', ['closed_timestamp'], unique=False
    )
    op.create_index(
        op.f('ix_issues_resolved_timestamp'),
        'issues',
        ['resolved_timestamp'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_resolved_timestamp'), table_name='issues')
    op.drop_index(op.f('ix_issues_closed_timestamp'), table_name='issues')
    op.drop_column('issues', 'resolved_timestamp')
    op.drop_column('issues', 'closed_timestamp')
    # ### end Alembic commands ###
