"""Add is_read column in notifications table

Revision ID: 812ebd486003
Revises: ab569cb9bd7a
Create Date: 2020-06-26 16:47:56.985125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812ebd486003'
down_revision = 'ab569cb9bd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.execute("UPDATE notifications SET is_read = FALSE;")
    op.alter_column('notifications', 'is_read', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###
