"""Delete role column and add index for projects title

Revision ID: c0cece3f665c
Revises: 52c7a230f63e
Create Date: 2020-05-15 00:33:05.154864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cece3f665c'
down_revision = '52c7a230f63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.drop_column('user_project', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_project',
        sa.Column('role', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    # ### end Alembic commands ###
