"""Add one to many relationship between user_project and roles table

Revision ID: cc0c59c188e4
Revises: 0c23633c2017
Create Date: 2020-05-19 11:05:15.709961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0c59c188e4'
down_revision = '0c23633c2017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project', sa.Column('role_id', sa.Integer(), nullable=True))
    op.execute("UPDATE user_project SET role_id = 1;")
    op.alter_column('user_project', 'role_id', nullable=False)
    op.create_foreign_key(None, 'user_project', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project', type_='foreignkey')
    op.drop_column('user_project', 'role_id')
    # ### end Alembic commands ###
