"""Change the name of users table's primary key to id

Revision ID: d753a8f0f639
Revises: 33dab1eda484
Create Date: 2020-05-10 22:42:13.876472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd753a8f0f639'
down_revision = '33dab1eda484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column('id', sa.String(), nullable=False, primary_key=True)
        )
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column('user_id', sa.VARCHAR(), nullable=False, primary_key=True)
        )
        batch_op.drop_column('id')
    # ### end Alembic commands ###
